version: "2"

services:
  mariadb:
    image: wodby/drupal-mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./docker-runtime/mariadb:/var/lib/mysql
#    ports:
#      - "3306:3306"

  php:
    image: fortis/stackd-php
    environment:
      PHP_SITE_NAME: dev
      PHP_HOST_NAME: localhost:7000
#      PHP_DOCROOT: web # Relative path inside the /var/www/html/ directory.
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_XDEBUG_ENABLED: 0
    volumes:
      - ./:/var/www/html

  nginx:
    image: fortis/stackd-nginx
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_UPSTREAM_NAME: php
      NGINX_DOCROOT: web
      DRUPAL_VERSION: 8
    volumes_from:
      - php
    ports:
      - "8080:80"

  solr:
    image: solr:6.2-alpine
    volumes:
#      - ./docker-runtime/solr:/opt/solr/server/solr/mycores/projects
      - ./docker-runtime/solr-init.sh:/docker-entrypoint-initdb.d/solr-init.sh
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - projects
    ports:
      - "2095:8983"
