version: "2"

services:
  mariadb:
    image: wodby/drupal-mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./docker-runtime/mariadb:/var/lib/mysql
#    ports:
#      - "3306:3306"

  php:
    image: fortis/stackd-php
    volumes:
      - ./:/var/www/html
    command: sh -c "composer install && php bin/console m6web:http-process --host php 7000"
    ports:
      - "8080:7000"

  solr:
    image: solr:6.2-alpine
    volumes:
#      - ./docker-runtime/solr:/opt/solr/server/solr/mycores/projects
      - ./docker-runtime/solr-init.sh:/docker-entrypoint-initdb.d/solr-init.sh
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - projects
    ports:
      - "2095:8983"
